### ISSUE TITLE
No need for request frame, but maybe echo frame

### ISSUE THREAD

**Issue by huitema** [martinthomson/train-protocol#21]
Section 7.2 includes "TODO: Define a new frame type for requesting that a peer send a TRAIN packet", but I do not think that this is needed. TRAIN is asymmetric: the opportunities created by a TRAIN sender measure the rate limits applicable to that sender. The sender can chose to send as many TRAIN as necessary for the local rate management. 

On the other hand, we may need to define an "echo" frame to send the measured values back to the peer.

**Comment by martinthomson** [comment]
I agree about the sender side of this: a sender can decide how often it wants to make an opportunity to mark, if at all.

**Comment by huitema** [comment]
Let's leave this open as we debate the feedback part, or its absence.
